services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: conexao
      POSTGRES_PASSWORD: conexao123
      POSTGRES_DB: conexao_campanhas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conexao -d conexao_campanhas"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: src/Campanhas.Api/Dockerfile
    ports:
      - "43123:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=conexao_campanhas;Username=conexao;Password=conexao123
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: "5672"
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      Jwt__Key: ConexaoSolidaria_SuperSecret_Key_ChangeInProd_32+
      Jwt__Issuer: conexao-solidaria
      Jwt__Audience: conexao-solidaria-clients
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: src/Doacoes.Worker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=conexao_campanhas;Username=conexao;Password=conexao123
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: "5672"
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      Metrics__Port: "8081"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  pgdata:
